// Generated by CoffeeScript 1.10.0
(function() {
  var i, j, k, l, len, len1, li, log, m, myFunc, outer, ref, ref1, ul1, ul2;

  log = function(str) {
    return console.log(str);
  };

  ul1 = document.getElementById('ul1');

  ref = ul1.querySelectorAll('li');
  for (j = 0, len = ref.length; j < len; j++) {
    li = ref[j];
    li.addEventListener('click', function(e) {
      return log(li.innerText);
    });
  }

  ul2 = document.getElementById('ul2');

  ref1 = ul2.querySelectorAll('li');
  for (k = 0, len1 = ref1.length; k < len1; k++) {
    li = ref1[k];
    li.addEventListener('click', (function(li) {
      return function(e) {
        return log(li.innerText);
      };
    })(li));
  }

  outer = function() {
    var x;
    x = 1;
    return function() {
      log("outer: " + x);
      return x = x + 1;
    };
  };

  myFunc = outer();

  myFunc();

  myFunc();

  myFunc();

  for (i = l = 1; l <= 3; i = ++l) {
    setTimeout(function() {
      return log("setTimeout1: " + i);
    }, 100);
  }

  for (i = m = 1; m <= 3; i = ++m) {
    setTimeout((function(i) {
      return function() {
        return log("setTimeout1: " + i);
      };
    })(i), 200);
  }

}).call(this);
