assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: "/code-memo/"

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

#ga_analytics: UA-xxxxxxxx-xx

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-coffeescript

markdown: kramdown

title: Mitsuru793
email: your-email@domain.com
description: >
  テストコードや、コードリーディングのメモを置いています。
url: "http://mitsuru793.github.io"
twitter_username: mitsuru793
github_username: mitsuru793
collections:
  codes:
    output: true
