// Generated by CoffeeScript 1.10.0
(function() {
  var appendAfter, appendBefore, createLi, lis, log;

  log = function(string) {
    return console.log(string);
  };

  appendBefore = function(element, insertElement) {
    return element.parentNode.insertBefore(insertElement, element);
  };

  appendAfter = function(element, insertElement) {
    return element.parentNode.insertBefore(insertElement, element.nextSibling);
  };

  createLi = (function() {
    var liEl;
    liEl = document.createElement('li');
    return function(string) {
      var newLiEl;
      newLiEl = liEl.cloneNode(false);
      newLiEl.innerText = string;
      return newLiEl;
    };
  })();

  lis = document.querySelectorAll('#ul1 > li');

  appendBefore(lis[0], createLi('0'));

  appendAfter(lis[0], createLi('1.5'));

}).call(this);
